In [1]:
import numpy as np
import pandas as pd
from pathlib import Path
from datetime import datetime

In [2]:
# Feed teh data from Coinbase API to obtain our list of transaction
# In our case we will use a fake portfolio of transactions stored in a CSV. 
# The format of this CSV file is teh same as the one generated by the Coinbase API

# Read into the transaction CSV file 
filepath= Path('Coinbase/cb_buy_data.csv')
tx_df= pd.read_csv(filepath, parse_dates=True, infer_datetime_format=True)
tx_df= tx_df.set_index("buy_date", drop=True)
tx_df= tx_df.drop(columns=['Unnamed: 0','payment_method_id','payment_method_resource',
                           'tx_id','tx_resource','buy_update_date',
                           'buy_committed','buy_payout_date','buy_instant', 'buy_status', 
                           'buy_total_currency', 'buy_sub_total_currency'])

# Read into the marketdata - coins prices CSV file 
filepath2= Path('coins_prices_data.csv')
px_df= pd.read_csv(filepath2, parse_dates=True, infer_datetime_format=True)
px_df= px_df.set_index("Unnamed: 0", drop=True)
px_df.index.names = ['Date']


px_df.head()
# amount = Amount in bitcoin, bitcoin cash, litecoin or ethereum
# subtotal = Fiat amount without fees

                btc-usd     eth-usd  link-usd   ada-usd
Date
2020-03-12  4970.788086  112.347122  2.064779  0.023961
2020-03-13  5563.707031  133.201813  2.421135  0.028437
2020-03-14  5200.366211  123.306023  2.143518  0.026009
2020-03-15  5392.314941  125.214302  2.109211  0.027120
2020-03-16  5014.479980  110.605873  1.779877  0.024121

In [3]:
# add fees and "price" columns
tx_df['$ price']= round(tx_df['buy_sub_total']/tx_df['buy_amount'],4)
tx_df['$ fees']= tx_df['buy_total'] - tx_df['buy_sub_total']
tx_df= tx_df.drop(columns=['buy_sub_total'])
tx_df.head()

,buy_amount,buy_amount_currency,buy_total,resource,$ price,$ fees
buy_date,,,,,,
2021-08-27 01:10:24+00:00,0.365094,DOT,10,buy,24.6786,0.99
2021-08-20 02:28:04+00:00,0.333743,DOT,10,buy,26.9969,0.99
2021-08-13 03:36:17+00:00,0.420890,DOT,10,buy,21.4070,0.99
2021-08-06 01:17:38+00:00,0.479346,DOT,10,buy,18.7964,0.99
2021-07-30 03:15:52+00:00,0.578896,DOT,10,sell,15.5641,0.99

In [4]:
# list of coins I transacted: 
tx_coins = list(tx_df['buy_amount_currency'].unique())
print('You traded {} different coins'.format(len(tx_coins)))

You traded 11 different coins

In [10]:
tx_df['cash_flow']= np.where(tx_df['resource']== 'buy', (-1*tx_df['buy_total']), tx_df['buy_total'])
tx_df['units']= np.where(tx_df['resource']== 'buy', (tx_df['buy_amount']), (-1*tx_df['buy_amount']))
tx_df.head()

,buy_amount,buy_amount_currency,buy_total,resource,$ price,$ fees,cash_flow,units
buy_date,,,,,,,,
2021-08-27 01:10:24+00:00,0.365094,DOT,10,buy,24.6786,0.99,-10,0.365094
2021-08-20 02:28:04+00:00,0.333743,DOT,10,buy,26.9969,0.99,-10,0.333743
2021-08-13 03:36:17+00:00,0.420890,DOT,10,buy,21.4070,0.99,-10,0.420890
2021-08-06 01:17:38+00:00,0.479346,DOT,10,buy,18.7964,0.99,-10,0.479346
2021-07-30 03:15:52+00:00,0.578896,DOT,10,sell,15.5641,0.99,10,-0.578896

,buy_amount,buy_amount_currency,buy_total,resource,$ price,$ fees,cash_flow,units,average_price
buy_date,,,,,,,,,
2021-08-27 01:10:24+00:00,0.365094,DOT,10,buy,24.6786,0.99,-10,0.365094,24.6786
2021-08-20 02:28:04+00:00,0.333743,DOT,10,buy,26.9969,0.99,-10,0.333743,26.9969
2021-08-13 03:36:17+00:00,0.420890,DOT,10,buy,21.4070,0.99,-10,0.420890,21.4070
2021-08-06 01:17:38+00:00,0.479346,DOT,10,buy,18.7964,0.99,-10,0.479346,18.7964
2021-07-30 03:15:52+00:00,0.578896,DOT,10,sell,15.5641,0.99,10,-0.578896,15.5641

                              cash_flow       units  average_price         PnL
buy_amount_currency resource
1INCH               buy            -200   40.190605       4.830500  194.140715
                    sell             75  -40.190605       1.702750  -68.434552
ADA                 buy             -65   46.663820       1.309000   61.082940
                    sell             25  -15.757129       1.492000  -23.509636
AMP                 buy             -70  791.900665       0.065920   52.202092
                    sell             10 -138.905130       0.057700   -8.014826
DAI                 buy            -180  169.808607       1.014933  172.344415
DOT                 buy             -60    2.857987      20.104283   57.457780
                    sell             40   -2.407334      14.971700  -36.041881
ENJ                 buy             -80   57.040365       1.337917   76.315255
GRT                 buy            -280  249.033605       0.764892  190.483889
                    sell             20  -23.195647       0.604825  -14.029307
KEEP                buy             -50   90.155323       0.521550   47.020509
MANA                buy             -25   36.781501       0.639200   23.510736
MATIC               buy            -100   80.509603       1.160033   93.393823
                    sell            130 -100.606280       1.211325 -121.866903
UNI                 buy            -100   14.898267       6.511500   97.010067

In [32]:
tx_pnl_df= tx_df2.groupby(['buy_amount_currency']).agg({'cash_flow': 'sum',
                                                'units': 'sum',
                                                'average_price':'mean',
                                                 'PnL': 'sum'
                                                })
tx_pnl_df

                     cash_flow       units  average_price         PnL
buy_amount_currency
1INCH                     -125    0.000000       3.266625  125.706163
ADA                        -40   30.906691       1.400500   37.573304
AMP                        -60  652.995534       0.061810   44.187266
DAI                       -180  169.808607       1.014933  172.344415
DOT                        -20    0.450653      17.537992   21.415898
ENJ                        -80   57.040365       1.337917   76.315255
GRT                       -260  225.837958       0.684859  176.454581
KEEP                       -50   90.155323       0.521550   47.020509
MANA                       -25   36.781501       0.639200   23.510736
MATIC                       30  -20.096678       1.185679  -28.473080
UNI                       -100   14.898267       6.511500   97.010067

In [44]:
## Show a table with our last position 

last_positions = tx_df.groupby(['buy_amount_currency']).agg({'units': 'sum', 'cash_flow': 'sum',
#                                                 'gain_loss': 'sum', 
                                                             }).reset_index()
last_positions

curr_prices = []
for coin in tx_coins:
    price = px_df[coin].iloc[-1]
    curr_prices.append(price)
    print(f'Done for {coin}')
len(curr_prices)


last_positions['price'] = curr_prices
last_positions['current_value'] = (last_positions.price * last_positions.units).round(2)
last_positions = last_positions.sort_values(by='current_value', ascending=False)

last_positions

KeyError: 'DOT'

In [38]:
px_df['btc-usd'].iloc[-1]

10774.4267578125

KeyError: 'gain_loss'

In [37]:
tx_df['buy_amount_currency'].iloc[-1]

'DAI'

KeyError: "None of [Index(['date', 'ticker', 'cashflow', 'cml_units', 'cml_cost', 'gain_loss'], dtype='object')] are in the [columns]"